In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('naukri_com-job_sample.csv')
df.head()

company  \
0                            MM Media Pvt Ltd   
1                          find live infotech   
2         Softtech Career Infosystem Pvt. Ltd   
3                      Onboard HRServices LLP   
4  Spire Technologies and Solutions Pvt. Ltd.   

                                           education   experience  \
0  UG: B.Tech/B.E. - Any Specialization PG:Any Po...    0 - 1 yrs   
1  UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...    0 - 0 yrs   
2  UG: Any Graduate - Any Specialization PG:Any P...    4 - 8 yrs   
3  UG: Any Graduate - Any Specialization PG:CA Do...  11 - 15 yrs   
4  UG: B.Tech/B.E. - Any Specialization PG:Any Po...    6 - 8 yrs   

                                   industry  \
0          Media / Entertainment / Internet   
1  Advertising / PR / MR / Event Management   
2           IT-Software / Software Services   
3    Banking / Financial Services / Broking   
4           IT-Software / Software Services   

                                      jobdescription         jobid  \
0  Job Description   Send me Jobs like this Quali...  210516002263   
1  Job Description   Send me Jobs like this Quali...  210516002391   
2  Job Description   Send me Jobs like this - as ...  101016900534   
3  Job Description   Send me Jobs like this - Inv...   81016900536   
4  Job Description   Send me Jobs like this Pleas...  120916002122   

                                 joblocation_address  \
0                                            Chennai   
1                                            Chennai   
2                                          Bengaluru   
3  Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...   
4                                          Bengaluru   

                                   jobtitle  numberofpositions  \
0  Walkin Data Entry Operator (night Shift)                NaN   
1        Work Based Onhome Based Part Time.               60.0   
2                    Pl/sql Developer - SQL                NaN   
3    Manager/ad/partner - Indirect Tax - CA                NaN   
4           JAVA Technical Lead (6-8 yrs) -                4.0   

                          payrate                   postdate site_name  \
0         1,50,000 - 2,25,000 P.A  2016-05-21 19:30:00 +0000       NaN   
1  1,50,000 - 2,50,000 P.A. 20000  2016-05-21 19:30:00 +0000       NaN   
2      Not Disclosed by Recruiter  2016-10-13 16:20:55 +0000       NaN   
3      Not Disclosed by Recruiter  2016-10-13 16:20:55 +0000       NaN   
4      Not Disclosed by Recruiter  2016-10-13 16:20:55 +0000       NaN   

                                  skills                           uniq_id  
0                                   ITES  43b19632647068535437c774b6ca6cf8  
1                              Marketing  d4c72325e57f89f364812b5ed5a795f0  
2  IT Software - Application Programming  c47df6f4cfdf5b46f1fd713ba61b9eba  
3                               Accounts  115d28f140f694dd1cc61c53d03c66ae  
4  IT Software - Application Programming  a12553fc03bc7bcced8b1bb8963f97b4

In [2]:
df.shape

(22000, 14)

In [3]:
df.describe()

jobid  numberofpositions
count  2.200000e+04        4464.000000
mean   1.561171e+11          45.116935
std    9.423956e+10         186.197193
min    1.011600e+10           1.000000
25%    6.121650e+10           2.000000
50%    1.602169e+11           4.000000
75%    2.502166e+11          10.000000
max    3.112155e+11        2000.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
company                21996 non-null object
education              20004 non-null object
experience             21996 non-null object
industry               21995 non-null object
jobdescription         21996 non-null object
jobid                  22000 non-null int64
joblocation_address    21499 non-null object
jobtitle               22000 non-null object
numberofpositions      4464 non-null float64
payrate                21903 non-null object
postdate               21977 non-null object
site_name              3987 non-null object
skills                 21472 non-null object
uniq_id                22000 non-null object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.3+ MB


In [5]:
df['company'] = df['company'].astype(str)
df['education'] = df['education'].astype(str)
df['experience'] = df['experience'].astype(str)
df['industry'] = df['industry'].astype(str)
df['jobdescription'] = df['jobdescription'].astype(str)
df['jobid'] = df['jobid'].astype(str)
df['joblocation_address'] = df['joblocation_address'].astype(str)
df['jobtitle'] = df['jobtitle'].astype(str)
df['numberofpositions'] = df['numberofpositions'].astype(str)
df['payrate'] = df['payrate'].astype(str)
df['postdate'] = df['postdate'].astype(str)
df['site_name'] = df['site_name'].astype(str)
df['skills'] = df['skills'].astype(str)
df['uniq_id'] = df['uniq_id'].astype(str)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
company                22000 non-null object
education              22000 non-null object
experience             22000 non-null object
industry               22000 non-null object
jobdescription         22000 non-null object
jobid                  22000 non-null object
joblocation_address    22000 non-null object
jobtitle               22000 non-null object
numberofpositions      22000 non-null object
payrate                22000 non-null object
postdate               22000 non-null object
site_name              22000 non-null object
skills                 22000 non-null object
uniq_id                22000 non-null object
dtypes: object(14)
memory usage: 2.3+ MB


In [7]:
from sklearn.preprocessing import LabelEncoder

# convert str values to int using the scikit-learn encoder

st = df.apply(LabelEncoder().fit_transform)

st.head()
df = st

In [8]:
X = df.iloc[:,:-1].values
y = df.iloc[:,1].values

In [9]:
X

array([[4286, 1239,    1, ..., 2907,    0,   29],
       [8267, 1301,    0, ..., 2907,    0,   32],
       [6684,   85,  113, ..., 3319,    0,   14],
       ...,
       [4685, 1244,   87, ..., 3743,    1,   14],
       [1628, 1336,  130, ..., 3761,    1,   14],
       [1309, 1334,  115, ..., 3743,    1,   25]])

In [10]:
y

array([1239, 1301,   85, ..., 1244, 1336, 1334])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 1/3, random_state = 0)

In [12]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
y_pred = regressor.predict(X_test)

In [14]:
from sklearn.metrics import mean_squared_error , r2_score
mse = mean_squared_error(y_test,y_pred)
r_squared = r2_score(y_test,y_pred)
print(mse)
print(r_squared)

3.80093874115059e-24
1.0


In [15]:
import statsmodels
import statsmodels.api as smf
regressorlm = X_train 
regressorlm = smf.add_constant(regressorlm)
# create a fitting model in one time
regressorlm=smf.OLS(y_train,regressorlm).fit()
regressorlm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.608e+32
Date:                Thu, 12 Dec 2019   Prob (F-statistic):               0.00
Time:                        18:36:50   Log-Likelihood:             3.7638e+05
No. Observations:               14666   AIC:                        -7.527e+05
Df Residuals:                   14652   BIC:                        -7.526e+05
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.411e-13   9.53e-14     -3.580      0.000   -5.28e-13   -1.54e-13
x1          3.556e-17   5.96e-18      5.970      0.000    2.39e-17    4.72e-17
x2             1.0000   1.82e-17   5.51e+16      0.000       1.000       1.000
x3          4.455e-15   3.22e-16     13.835      0.000    3.82e-15    5.09e-15
x4          1.144e-14   1.04e-15     11.039      0.000     9.4e-15    1.35e-14
x5         -6.755e-17   2.35e-18    -28.699      0.000   -7.22e-17   -6.29e-17
x6          9.606e-17   2.33e-18     41.183      0.000    9.15e-17    1.01e-16
x7         -8.101e-16    2.2e-17    -36.800      0.000   -8.53e-16   -7.67e-16
x8          4.169e-17   2.84e-18     14.677      0.000    3.61e-17    4.73e-17
x9           2.29e-15   5.81e-16      3.940      0.000    1.15e-15    3.43e-15
x10        -4.545e-16   3.71e-17    -12.237      0.000   -5.27e-16   -3.82e-16
x11        -8.934e-17   1.51e-17     -5.921      0.000   -1.19e-16   -5.98e-17
x12        -6.395e-14   5.44e-14     -1.176      0.239    -1.7e-13    4.26e-14
x13        -4.163e-16    1.2e-15     -0.346      0.730   -2.78e-15    1.94e-15
==============================================================================
Omnibus:                      397.218   Durbin-Watson:                   1.063
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              215.072
Skew:                           0.111   Prob(JB):                     1.98e-47
Kurtosis:                       2.450   Cond. No.                     1.30e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.3e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
regressor.intercept_

6.821210263296962e-13

In [17]:
regressor.coef_

array([-4.46495415e-18,  1.00000000e+00,  7.50849543e-16, -2.65790239e-15,
        1.97755046e-16, -1.89274410e-16, -3.17320845e-17, -6.71303525e-17,
       -1.54561803e-16, -7.28031916e-16,  2.45190056e-17,  9.05156548e-16,
        8.18406728e-17])